export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_CREATE_POST_REQUEST = "USER_CREATE_POST_REQUEST";
export const USER_CREATE_POST_FAIL = "USER_CREATE_POST_FAIL";
export const USER_CREATE_POST_SUCCESS = "USER_CREATE_POST_SUCCESS";
