const dummyData = [
  {
    userName: "ldrewclifton0",
    profile_photo: null,
    likes: 63,
    comments: null,
    shares: 97,
    isSaved: "false",
  },
  {
    userName: "awarre1",
    profile_photo: null,
    likes: 45,
    comments: null,
    shares: 31,
    isSaved: "false",
  },
  {
    userName: "harends2",
    profile_photo: null,
    likes: 31,
    comments: null,
    shares: 110,
    isSaved: "false",
  },
  {
    userName: "fvasnev3",
    profile_photo: null,
    likes: 97,
    comments: null,
    shares: 31,
    isSaved: "false",
  },
  {
    userName: "mklimko4",
    profile_photo: null,
    likes: 81,
    comments: null,
    shares: 45,
    isSaved: "false",
  },
  {
    userName: "dstannering5",
    profile_photo: null,
    likes: 20,
    comments: null,
    shares: 50,
    isSaved: "false",
  },
  {
    userName: "dpierro6",
    profile_photo: null,
    likes: 97,
    comments: null,
    shares: 110,
    isSaved: "false",
  },
  {
    userName: "mbreffitt7",
    profile_photo: null,
    likes: 20,
    comments: null,
    shares: 99,
    isSaved: "false",
  },
  {
    userName: "mwoodison8",
    profile_photo: null,
    likes: 110,
    comments: null,
    shares: 97,
    isSaved: "false",
  },
  {
    userName: "aminton9",
    profile_photo: null,
    likes: 81,
    comments: null,
    shares: 81,
    isSaved: "false",
  },
];

export default dummyData;
